default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tournaments_development

test:
  <<: *default
  database: tournaments_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: tournaments_production
  username: tournaments
  password: <%= ENV["TOURNAMENTS_DATABASE_PASSWORD"] %>